SELECT * FROM MEMBER;

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30),
    BIRTH DATE,
    GENDER VARCHAR2(30),
    EMAIL VARCHAR2(30) UNIQUE,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(30) );
    
INSERT INTO MEMBER VALUES ('aaa','111','dd',sysdate,'m','ma','010','주소');
commit;

SELECT * FROM MEMBER;

SELECT * FROM MEMBER WHERE ID=?;