DROP TABLE BOOK;
DROP TABLE BOOKKIND;
CREATE TABLE BOOKKIND(
	BOOK_KIND NUMBER(3) PRIMARY KEY,
	KIND_NAME VARCHAR2(30),
	LOCATION VARCHAR2(50)
)
CREATE TABLE BOOK(
	BOOK_ID VARCHAR2(30) PRIMARY KEY,
	BOOK_KIND NUMBER(3) REFERENCES BOOKKIND(BOOK_KIND),
	BOOK_TITLE VARCHAR2(60) NOT NULL,
	BOOK_PRICE NUMBER(6) NOT NULL,
	BOOK_COUNT NUMBER(6) NOT NULL,
	AUTHOR VARCHAR2(30) NOT NULL,
	PUBLISHING_COM VARCHAR2(30) NOT NULL,
	PUBLISHING_DATE DATE NOT NULL,
	BOOK_IMAGE1 VARCHAR2(30) DEFAULT 'NOTHING.JPG' NOT NULL,
	BOOK_IMAGE2 VARCHAR2(30) DEFAULT 'noImg.png' NOT NULL,
	BOOK_CONTENT VARCHAR2(4000), --책 소개
	BOOK_DISCOUNT NUMBER(3) DEFAULT 0,
	BOOK_RDATE DATE DEFAULT SYSDATE
);
SELECT * FROM BOOKKIND;
SELECT * FROM BOOK;

DROP TABLE BOOK;
DROP SEQUENCE BOOK_SEQ;
CREATE SEQUENCE BOOK_SEQ
    MAXVALUE 9999999
    NOCYCLE
    NOCACHE;


CREATE TABLE BOOK(
	bID NUMBER(7) PRIMARY KEY,
    bTITLE VARCHAR2(30) NOT NULL,
    bPRICE NUMBER(7) NOT NULL,
    bIMAGE1 VARCHAR2(30) DEFAULT 'NOTHING.JPG' NOT NULL,
    bIMAGE2 VARCHAR2(30) DEFAULT 'noImg.png' NOT NULL,
    bCONTENT VARCHAR2(4000),
    bDISCOUNT NUMBER(3) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE
);
SELECT * FROM BOOK;

-- 책등록
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 자바다',20000,'NOTHING.JPG','noImg.png','내용',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 JSP다',18000,'NOTHING.JPG','내용',10);    
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '오라클',19000,'noImg.png','내용',10);  
INSERT INTO BOOK (bID, bTITLE, bPRICE, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '오라',20000,'내용',10);    
-- 책목록(bRDATE - TOP-N)

SELECT * FROM BOOK ORDER BY bRDATE DESC;
SELECT ROWNUM RN, C.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) C;
SELECT * FROM (SELECT ROWNUM RN, C.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) C)
    WHERE RN BETWEEN 6 AND 10;
--등록된 책 갯수
SELECT COUNT(*) FROM BOOK;
commit;


--bID로 책 가져오기
SELECT * FROM BOOK WHERE bID='';











