DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    CID VARCHAR2(30) PRIMARY KEY,
    CPW VARCHAR2(30) NOT NULL,
    CNAME VARCHAR2(30) NOT NULL,
    CTEL VARCHAR2(30) NOT NULL,
    CEMAIL VARCHAR2(100),
    CADDRESS VARCHAR2(100),
    CGENDER VARCHAR2(1) NOT NULL,
    CBIRTH DATE,
    CRDATE DATE DEFAULT SYSDATE);
    
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (CID,CPW,CNAME,CTEL,CEMAIL,CADDRESS,CGENDER,CBIRTH) VALUES ('CID','CPW','CNAME','CTEL','CEMAIL','CADDRESS','M',NULL);

UPDATE CUSTOMER SET CPW='TEST11' WHERE CID='CID';
COMMIT;