DROP TABLE CART;
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;






CREATE TABLE PRODUCT(
    pCODE VARCHAR2(5) PRIMARY KEY,
    pNAME VARCHAR2(50),
    pPRICE NUMBER(9),
    pSTOCK NUMBER(3) );


CREATE TABLE MEMBER(
    mNO VARCHAR2(10) PRIMARY KEY,
    mNAME VARCHAR2(50),
    mADDR VARCHAR2(255),
    mTEL VARCHAR2(30),
    nMAIL VARCHAR2(40) );

CREATE TABLE CART(
    cNO NUMBER(4) PRIMARY KEY,
    mNO VARCHAR(10) REFERENCES MEMBER(mNO),
    pCODE VARCHAR2(5) REFERENCES PRODUCT(pCODE),
    QTY NUMBER(3),
    COST NUMBER(9) );
    
CREATE TABLE ORDERS(
    oNO NUMBER PRIMARY KEY,
    mNO VARCHAR2(10) REFERENCES MEMBER(mNO),
    oADDR VARCHAR2(255),
    oTEL VARCHAR(30),
    oDATE DATE );

CREATE TABLE ORDERDETAIL(
    odNO NUMBER(4) PRIMARY KEY,
    oNO NUMBER REFERENCES ORDERS(oNO),
    pCODE VARCHAR2(5) REFERENCES PRODUCT(pCODE),
    QTY NUMBER(3),
    COST NUMBER(9) );
    
INSERT INTO member VALUES('123','1','33','42','123');    
DELETE FROM member;
     