DROP TABLE BOARD;
CREATE TABLE BOARD(
    ID NUMBER(4) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(1000),
    bGROUP NUMBER(4) NOT NULL,
    STEP NUMBER(4) NOT NULL,
    INDENT NUMBER(4) NOT NULL
);
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ;
INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL,  '글1',NULL,BOARD_SEQ.CURRVAL, 0,0);
INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL,  '글2',NULL,BOARD_SEQ.CURRVAL, 0,0);
INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL,  '글3',NULL,BOARD_SEQ.CURRVAL, 0,0);
--답글
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글1-1',NULL, 1,1,1); -- 글1의 첫답글
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글2-1',NULL, 2,1,1); -- 글2의 첫답글
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글3-1',NULL, 3,1,1); -- 글3의 첫답글
UPDATE BOARD SET STEP = STEP+1 WHERE bGROUP=2 AND STEP>0;-- 글2의 두번째 답글달기전 A STEP
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글2-2',NULL, 2,1,1); -- 글2의 두번째 답글
UPDATE BOARD SET STEP = STEP+1 WHERE bGROUP=2 AND STEP>0;-- 글2의 세번째 답글달기전 A STEP
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글2-3',NULL, 2,1,1); -- 글2의 세번째 답글
UPDATE BOARD SET STEP = STEP+1 WHERE bGROUP=2 AND STEP>1;-- 글2-3의 첫번째 답글(답변의 답변)달기전 A STEP
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글2-3-1',NULL, 2,2,2); -- 글2-3의 첫번째 답글(답변의 답변)
UPDATE BOARD SET STEP = STEP+1 WHERE bGROUP=2 AND STEP>0;-- 글2의 네번째 답글달기전 A STEP
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '글2-4',NULL, 2,1,1); -- 글2의 네번째 답글
-- 글 보기(들여쓰기 반영)
SELECT ID, (SELECT LPAD('└', INDENT*2) FROM BOARD WHERE B.ID=ID AND INDENT>0)||
    TITLE TITLE, BGROUP, STEP, INDENT
    FROM BOARD B ORDER BY bGROUP DESC, STEP;

-- 특정 글 삭제(글 2-3을 삭제할 시 글2-3과 글 2-3-1을 함께 삭제하고 그 아래 있는 STEP의 순서를 올린다) 
--     삭제할 글번호 : 8 / 글2-3 / 2(BGROUP) / 2(STEP) /1(INDENT) 
SELECT * FROM BOARD WHERE BGROUP=2 AND STEP>2 AND INDENT<=1; -- 삭제하려는 글들 밑에 있는 글(같은 그룹 중)
SELECT MIN(STEP) FROM BOARD WHERE BGROUP=2 AND STEP>2 AND INDENT<=1; -- 삭제후 step 순서를 올려야 하는 글 중 가장 작은 step
-- 지워야할 글 
SELECT * FROM BOARD 
    WHERE BGROUP=2 AND 
        (STEP>=2 AND STEP<(SELECT MIN(STEP) FROM BOARD WHERE BGROUP=2 AND STEP>2 AND INDENT<=1));
-- 글 지우기
DELETE FROM BOARD 
    WHERE BGROUP=2 AND 
        (STEP>=2 AND STEP<(SELECT MIN(STEP) FROM BOARD WHERE BGROUP=2 AND STEP>2 AND INDENT<=1));

-- 삭제하고 난 후 step 순서를 올려야 하는 글
UPDATE BOARD SET STEP = STEP-2 WHERE BGROUP=2 AND STEP>2;
SELECT * FROM BOARD ORDER BY bgroup DESC, STEP;

select * from board where id=4; -- 4번글을 지울때 - 지울 DTO :  4 / 글1-1 / 1(BGROUP) / 1(STEP) /1(INDENT)
SELECT NVL(MIN(STEP),9999) FROM BOARD WHERE BGROUP=1 AND STEP>1 AND INDENT<=1;

-- 결론
DELETE FROM BOARD WHERE BGROUP=1 AND (STEP>=1 AND STEP<(SELECT NVL(MIN(STEP),9999) FROM BOARD WHERE BGROUP=1 AND STEP>2 AND INDENT<=1)); 
-- 위의 결과 행수가 1라면
UPDATE BOARD SET STEP = STEP-1 WHERE BGROUP=1 AND STEP>2;

INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL, '글4','글4',BOARD_SEQ.CURRVAL, 0,0);
SELECT * FROM BOARD WHERE ID=11; -- 지울 11번글 DTO : 11/글11 / 11(bGROUP) / 0(STEP) / 0(INDENT)
-- ★ 결론 : 필요한 sql문 2개 위행이 수행 결과 1행 delete되면 아래단의 step는 1씩 줄인다
DELETE FROM BOARD WHERE BGROUP=11 AND (STEP>=0 AND STEP<(SELECT NVL(MIN(STEP),9999) FROM BOARD WHERE BGROUP=11 AND STEP>0 AND INDENT<=0));
UPDATE BOARD SET STEP = STEP-1 WHERE BGROUP=11 AND STEP>0; -- 위의 DELETE문 수행 결과가 1행인 경우