SELECT * FROM DEPT;
SELECT COUNT(*) FROM DEPT WHERE DEPTNO=30;
INSERT INTO DEPT VALUES (50,'MARKETING','SEOUL');
UPDATE DEPT SET DNAME='',LOC='' WHERE DEPTNO=10;
DELETE FROM DEPT WHERE DEPTNO=30;
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
SELECT * FROM DEPT;
UPDATE DEPT SET DNAME='GAMES',LOC='LOLOL' WHERE DEPTNO=60;

DELETE FROM DEPT WHERE DEPTNO=60;

SELECT * FROM DEPT WHERE DEPTNO=30;
COMMIT;



SELECT * FROM MAJOR;
SELECT * FROM STUDENT;
DROP TABLE STUDENT;
DROP TABLE MAJOR;
CREATE TABLE MAJOR(
    mNO NUMBER(1) PRIMARY KEY,
    mNAME VARCHAR(20) UNIQUE );

INSERT INTO MAJOR VALUES (1, '컴퓨터공학');
INSERT INTO MAJOR VALUES (2, '경영정보학');
INSERT INTO MAJOR VALUES (3, '산업디자인');
INSERT INTO MAJOR VALUES (4, '정보전자학');
INSERT INTO MAJOR VALUES (5, '연극영화학');	

CREATE SEQUENCE ST_SEQ
    NOCACHE;

CREATE TABLE STUDENT(
    sNO VARCHAR2(10) PRIMARY KEY,
    sNAME VARCHAR2(15),
    mNO NUMBER(1) REFERENCES MAJOR(mNO),
    SCORE NUMBER(3),
    sEXPEL NUMBER(1) );
-- sNO, sNAME, mNO, SCORE, sEXPEL
-- TO_CHAR(SYSDATE,'YYYY')||TO_CHAR(mNO,'00')||TO_CHAR(ST_SEQ.NEXTVAL ,'000')
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE,'YYYY')||LPAD(1 ,2,'0')||LPAD(ST_SEQ.NEXTVAL ,3,'0') , '홍길동',1,50,0);
SELECT * FROM STUDENT;




