DROP TABLE FRIEND;

CREATE TABLE FRIEND(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30),
    TEL VARCHAR2(30) UNIQUE );

DROP SEQUENCE FRIEND_SEQ;
    
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;
    
SELECT * FROM FRIEND;
SELECT * FROM FRIEND WHERE NAME LIKE '%'|| ''||'%' AND TEL LIKE '%'|| '1'||'%'
ORDER BY NO;
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, '아이유', '010-2344-8888');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, '유인나', '010-1111-1111');
commit;