DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30),
    BIRTH DATE NOT NULL,
    RDATE DATE NOT NULL,
    ADDRESS VARCHAR2(200) );
    
SELECT * FROM MEMBER;

-- 1.회원리스트
SELECT * FROM MEMBER;
-- 2.회원가입시 INSERT
INSERT INTO MEMBER (ID,PW,NAME,EMAIL,BIRTH,RDATE,ADDRESS) VALUES ('TID','TPW','TNAME','TEMAIL',SYSDATE,SYSDATE,'TADDR');

