DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT(
    PNO NUMBER(4) PRIMARY KEY,
    PNAME VARCHAR2(100) NOT NULL,
    PSTOCK NUMBER(4) NOT NULL
);

INSERT INTO PRODUCT VALUES (1,'공책',3);
INSERT INTO PRODUCT VALUES (2,'볼펜',10);
INSERT INTO PRODUCT VALUES (3,'지우개',13);

COMMIT;

SELECT * FROM PRODUCT WHERE PNAME='공책';


SELECT *FROM EMP WHERE ENAME LIKE '%'||'A'||'%' AND JOB LIKE '%'||'A'||'%';