DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30),
    BIRTH DATE NOT NULL,
    RDATE DATE NOT NULL,
    ADDRESS VARCHAR2(200) );
    
SELECT * FROM MEMBER;

-- 1.회원가입시 ID 중복체크
SELECT * FROM MEMBER WHERE ID='TID';
-- 2.회원가입시 INSERT
INSERT INTO MEMBER (ID,PW,NAME,EMAIL,BIRTH,RDATE,ADDRESS) VALUES ('TID','TPW','TNAME','TEMAIL',SYSDATE,SYSDATE,'TADDR');
-- 3.로그인 할 때 (ID있는지 있으면 PW 맞는지)
SELECT * FROM MEMBER WHERE ID='TID';
SELECT * FROM MEMBER WHERE ID='TID' AND PW='TPW';
-- 4.ID로 DTO가져오기
SELECT * FROM MEMBER WHERE ID='TID';
-- 5.회원정보수정
UPDATE MEMBER SET PW='TPW', NAME='TNAME', EMAIL='TEMAIL', BIRTH=SYSDATE, ADDRESS='TADDR' WHERE ID='TID';
COMMIT;

SELECT * FROM MEMBER;