SELECT * FROM EMP;

SELECT COUNT(*) FROM EMP;


SELECT * FROM EMP WHERE ENAME LIKE '%'||'M'||'%';

SELECT * FROM EMP WHERE ENAME LIKE '%'||'M'||'%' ORDER BY EMPNO;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM EMP WHERE ENAME LIKE '%'||'M'||'%' ORDER BY EMPNO));