SELECT * FROM EMP;

SELECT COUNT(*) FROM EMP;


SELECT * FROM EMP WHERE ENAME LIKE '%'||'M'||'%' AND JOB LIKE '%'||''||'%';

SELECT * FROM EMP WHERE ENAME LIKE '%'||'M'||'%' ORDER BY EMPNO;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM EMP WHERE ENAME LIKE '%'||''||'%' AND JOB LIKE '%'||''||'%' ORDER BY EMPNO) A)
    WHERE RN BETWEEN 5 AND 10;