DROP TABLE MVC_BOARD CASCADE CONSTRAINTS;
DROP SEQUENCE MVC_BOARD_SEQ;
CREATE TABLE MVC_BOARD(
    BID NUMBER(6),
    BNAME VARCHAR2(50) NOT NULL,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000),
    BDATE DATE DEFAULT SYSDATE NOT NULL,
    BHIT NUMBER(6) DEFAULT 0 NOT NULL,
    BGROUP NUMBER(6) NOT NULL,
    BSTEP NUMBER(3) NOT NULL,
    BINDENT NUMBER(3) NOT NULL,
    BIP VARCHAR2(20) NOT NULL,
    PRIMARY KEY(BID)
);
CREATE SEQUENCE MVC_BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

SELECT TO_CHAR(BDATE,'YYYY-MM-DD HH24:MI:SS') FROM mvc_board;

INSERT INTO mvc_board (BID, BNAME, BTITLE, BCONTENT, BDATE, BGROUP,BSTEP,BINDENT, BIP) VALUES 
    (MVC_BOARD_SEQ.NEXTVAL,'홍길동','제목','내용',SYSDATE,MVC_BOARD_SEQ.CURRVAL,0,0,'IP');
COMMIT;

-- 1. 글목록 (START_ROW ~ END_ROW)
SELECT * FROM (SELECT ROWNUM RN,A.* FROM (SELECT * FROM mvc_board ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 1 AND 50;
-- 2. 전체 글 갯수
SELECT COUNT(*) FROM mvc_board;
-- 3. 원글쓰기
INSERT INTO mvc_board (BID, BNAME, BTITLE, BCONTENT, BGROUP,BSTEP,BINDENT, BIP) VALUES 
    (MVC_BOARD_SEQ.NEXTVAL,'홍길동','제목','내용',MVC_BOARD_SEQ.CURRVAL,0,0,'IP');
INSERT INTO mvc_board (BID, BNAME, BTITLE, BCONTENT, BGROUP,BSTEP,BINDENT, BIP) VALUES 
    (MVC_BOARD_SEQ.NEXTVAL,'김길동','제목2','내용2',MVC_BOARD_SEQ.CURRVAL,0,0,'IP');
COMMIT;
-- 4. 상세글보기(BID)+조회수 1 올리기
UPDATE mvc_board SET BHIT=BHIT+1 WHERE BID=1;
SELECT * FROM mvc_board WHERE BID=1;

COMMIT;
-- 5. 답글쓰기 STEP A (원글 BGROUP BSTEP)
UPDATE mvc_board SET BSTEP=BSTEP+1 WHERE BGROUP=3 AND BSTEP>2;
-- 5. 답변글 쓰기 
INSERT INTO mvc_board (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL,'답변자','답글','답내용',2,1,1,'BIP');
COMMIT;
-- 6. 글 수정하기
UPDATE mvc_board SET BNAME='수정',BTITLE='수정제목',BCONTENT='수정내용',BDATE=SYSDATE,BIP='195.11' WHERE BID=1;

-- 7. 삭제하기
DELETE FROM mvc_board WHERE BID=1;

SELECT * FROM mvc_board;







