DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
	CID VARCHAR2(50) PRIMARY KEY,
	CPW VARCHAR2(50) NOT NULL,
	CNAME VARCHAR2(50) NOT NULL,
	CTEL VARCHAR2(50) NOT NULL,
	CEMAIL VARCHAR2(50),
	CADDRESS VARCHAR2(250),
	CBIRTH DATE NOT NULL,
	CGENDER VARCHAR2(10) NOT NULL,
	CRDATE DATE DEFAULT SYSDATE
);

SELECT * FROM CUSTOMER;

--1.id중복체크
SELECT * FROM CUSTOMER WHERE CID='ID';
--2.회원가입
INSERT INTO CUSTOMER (CID,CPW,CNAME,CTEL,CEMAIL,CADDRESS,CBIRTH,CGENDER) VALUES 
('CID','CPW','CNAME','CTEL','CEMAIL','CADDRESS',TO_CHAR('1992-03-08','YYYY-MM-DD'),'m');
--3.로그인처리
SELECT * FROM CUSTOMER WHERE CID='ID' AND CPW='PW';
--4.id로 DTO가져오기
SELECT * FROM CUSTOMER WHERE CID='ID';
--5.회원정보수정
UPDATE CUSTOMER SET CPW='TEST11',CNAME='NAME',CTEL='TEL',CEMAIL='EMAIL',CADDRESS='ADDRESS',CBIRTH=SYSDATE,CGENDER='F' WHERE CID='CID';
COMMIT;