-- ★ 고객(Customer) 관련
SELECT * FROM CUSTOMER;

--1.id중복체크
SELECT * FROM CUSTOMER WHERE CID='CID';
--2.회원가입
INSERT INTO CUSTOMER (CID,CPW,CNAME,CTEL,CEMAIL,CADDRESS,CGENDER,CBIRTH) VALUES 
('CID3','CPW','CNAME','CTEL','CEMAIL','CADDRESS','m',SYSDATE);
--3.로그인처리
SELECT * FROM CUSTOMER WHERE CID='ID' AND CPW='PW';
--4.id로 DTO가져오기
SELECT * FROM CUSTOMER WHERE CID='ID';
--5.회원정보수정
UPDATE CUSTOMER SET CPW='TEST11',CNAME='NAME',CTEL='TEL',CEMAIL='EMAIL',CADDRESS='ADDRESS',CBIRTH=SYSDATE,CGENDER='F' WHERE CID='CID';
COMMIT;

-- 6.회원리스트 보기(start부터 end)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM CUSTOMER ORDER BY CID) A)
    WHERE RN BETWEEN 3 AND 5;
SELECT * FROM CUSTOMER;

-- 7.등록된 회원 명수 가져오기
SELECT COUNT(*) CNT FROM CUSTOMER;

-- ★ 책(Book) 관련

-- 1.책등록
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 자바다',20000,'NOTHING.JPG','noImg.png','내용',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 공짜다',10000,'NOTHING.JPG','noImg.png','내용',10);
-- 2.책목록(bRDATE - TOP-N)
SELECT * FROM (SELECT ROWNUM RN, C.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) C)
    WHERE RN BETWEEN 3 AND 5;
-- 3.등록된 책 갯수
SELECT COUNT(*) FROM BOOK;
commit;

-- 4.bID로 책 가져오기
SELECT * FROM BOOK WHERE bID='';


-- ★ 게시판(FileBoard) 관련

SELECT * FROM FILEBOARD;

-- 1.글목록(START,END)
SELECT * FROM FILEBOARD ORDER BY FREF DESC, FRE_STEP;
SELECT F.*,C.CNAME FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID ORDER BY FREF DESC, FRE_STEP;


SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT F.*,C.CNAME,C.CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID ORDER BY FREF DESC, FRE_STEP) A)
    WHERE RN BETWEEN 2 AND 3;
-- DAO에 쓸 쿼리

-- 2.등록된 글 갯수
SELECT COUNT(*) FROM FILEBOARD;

-- 3.글 추가(원글쓰기)
INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP,FRE_LEVEL,FIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL,'CID6','FSUBJECT','FCONTENT','FFILENAME','FPW',FILEBOARD_SEQ.CURRVAL,0,0,'FIP');

-- 4.글 추가(답글쓰기)
-- 답변글 쓰기 전 STEP-1 수행(REF가 같고 원글의 RE_STEP보다 많은 경우 RE_STEP++)
UPDATE FILEBOARD SET FRE_STEP=FRE_STEP+1 WHERE FREF=3 AND FRE_STEP>0;
SELECT * FROM FILEBOARD WHERE FREF = 3;


INSERT INTO FILEBOARD (FNUM, CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP,FRE_LEVEL,FIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL,'CID6','FSUBJECT','FCONTENT','FFILENAME','FPW',3,0+1,0+1,'FIP');

SELECT * FROM FILEBOARD ORDER BY FREF DESC, FRE_STEP;

-- 5.글 상세보기(글 번호로 DTO 가져오기)
SELECT F.*,C.CNAME,C.CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID AND FNUM=3;

-- 5-2 hit수 올리기
UPDATE FILEBOARD SET FHIT=FHIT+1 WHERE FNUM=3;


-- 6.글 수정하기
UPDATE FILEBOARD SET FSUBJECT='바뀐제목',FCONTENT='바뀐내용',FFILENAME='파일첨부',
    FPW='바뀐비번',FIP='바뀐IP' WHERE FNUM=3;
COMMIT;

-- 7.글 삭제
DELETE FROM FILEBOARD WHERE FNUM=3;
COMMIT;
SELECT * FROM FILEBOARD ORDER BY FREF DESC, FRE_STEP;
